site_name: 'Weisisheng FAQs -- Corporate, Career & Academic Clients'
repo_name: 'GitHub'
repo_url: 'https://github.com/weisisheng/wss-faq'
site_description: 'Weisisheng Client FAQ Built From MkDocs Material Boilerplate'
site_author: 'Vince Fulco, CFA, CAIA'
copyright: 'peaceiris'
theme:
  name: 'material'
  language: 'en'
  shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
  palette:
    primary: 'blue'
    accent: 'blue'
markdown_extensions:
    - admonition
    - codehilite
    - footnotes
    - mdx_math:
        enable_dollar_delimiter: True
    - toc:
        permalink: True
        separator: "_"
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
